### ISSUE TITLE
Public diagrams are NOT editable by everyone, but it's not clear

### ISSUE THREAD

**Issue by Bjarno** [ponyorm/editor#1]
Currently public diagrams can be edited by everyone with an account. This means that a possibly malicious user is able (as all public diagrams are visible on a single page) to destroy all diagrams.

This makes it difficult to rely on to make small projects, if at any given time, a malicious user can come in and destroy everything.

A possible improvement would be to restrict write access to diagrams. If someone wants to edit a diagram, he can make a copy of it and edit his own copy.

**Comment by amalashkevich** [comment]
Public diagrams are **not** editable by everyone. You can see any public diagram, that's true. If you open a public diagram of another user and click 'Save Diagram', then it will be cloned and saved under your account. In the same time, the original diagram will stay untouched.

**Comment by Bjarno** [comment]
Apologies. For a minute it really looked like this as I got no notification/mention about this. Maybe make it more clear in the user interface or require users to save/fork first before allowing any edits. 

But thanks for clearing this up.

**Comment by amalashkevich** [comment]
Agree, we can do it more clear.
Thanks for reporting!

**Comment by epogrebnyak** [comment]
Why not close this?

**Comment by Bjarno** [comment]
Indeed, I just noticed (it's a long time ago since I tried to do anything with Pony ORM) that a notification is shown when the user tries to change something in a public diagram. I will close it.
