### ISSUE TITLE
Sqlite database name is ignored, :memory: is always used

### ISSUE THREAD

**Issue by stenci** [ponyorm/editor#4]
The Python code for Sqlite database created with the online editor always ends with the following two lines:
```
db.bind("sqlite", ":memory:", create_db=True)
db.generate_mapping(create_tables=True)
```
I don't remember ever manually changing them. I think they came out with the correct database name, as set in the settings page. Also the two checkboxes in the mapping settings are ignored: "Create database" and "Create tables".

Is it a regression?

**Comment by amalashkevich** [comment]
It is a regression. Will deploy the fix tomorrow. Thanks!

**Comment by amalashkevich** [comment]
Should be fixed now.
